### ISSUE TITLE
[enhancement] Suggestion: add Partner resource

### ISSUE THREAD

**Issue by briankung** [Armor-Payments/armor_payments_ruby#2]
I have a branch sitting on my repo that adds a `Partner` resource. I fully intended on using this to retrive the list of extant users for a particular `Partner` to associate to our own users until I realized that it needed to have a more complex uri: `partner/:pid/users`. Then I reconsidered because I didn't know how to model that properly. I would have named it "PartnerUsers" or something like that, but the class name is used to generate the path.

I think I'm just going to end up just using `Resource` to access the url that I want with the proper URI. Thoughts?

https://github.com/briankung/armor_payments_ruby/tree/add-partners

**Comment by mrmarkfrench** [comment]
This is a perfectly reasonable use case. I'll get this added.

**Comment by mrmarkfrench** [comment]
I've just pushed a new Partner resource. It should take care of your basic use case, but it won't let you chain from the resources it returns like you might expect. I need to do some further work to make that possible (or to make it at least more gracefully handle the errors when it fails), but this should let you get started.

See commit 5f2be7a for a little bit more info on what I did.

**Comment by mrmarkfrench** [comment]
To be clear, you can call `client.partner.users(partner_id).all()` and it will work just fine. You just can't call `client.partner.users(partner_id).get(user_id)` to pull a single user.

The same is true of accounts. You can call `client.partner.accounts(partner_id).all()` but not `client.partner.accounts(partner_id).get(account_id)`.

**Comment by briankung** [comment]
Awesome, thanks!

**Comment by briankung** [comment]
I thought I had an issue, but it turns out that I was in sandbox mode. Closing!
