### ISSUE TITLE
NameError: undefined local variable or method `should_use_sandbox' for main:Object

### ISSUE THREAD

**Issue by nghiabk** [Armor-Payments/armor_payments_ruby#4]
have an error at this line. Please help me
client     = ArmorPayments::API.new 'your-key', 'your-secret', should_use_sandbox

**Comment by mrmarkfrench** [comment]
Did you pass a boolean value `true` or `false` to indicate if you did (or did not) want to make your API calls against the Sandbox environment?

**Comment by mrmarkfrench** [comment]
You can either replace `should_use_sandbox` with a boolean literal, or you can define `should_use_sandbox` with a boolean value.
